var words = [
    {
        h:"红色",
        e:"red",
        src:"assets/mp3/danci/red.mp3"
    },
    {
        h:"绿色",
        e:"green",
        src:"assets/mp3/danci/green.mp3"
    },
    {
        h:"蓝色",
        e:"blue",
        src:"assets/mp3/danci/blue.mp3"
    },
    {
        h:"橙色",
        e:"orange",
        src:"assets/mp3/danci/orange.mp3"
    },
    {
        h:"白色",
        e:"white",
        src:"assets/mp3/danci/white.mp3"
    },
    {
        h:"黑色",
        e:"black",
        src:"assets/mp3/danci/black.mp3"
    },
    {
        h:"灰色",
        e:"gray",
        src:"assets/mp3/danci/gray.mp3"
    },
    {
        h:"紫色",
        e:"purple",
        src:"assets/mp3/danci/purple.mp3"
    },
    {
        h:"金色",
        e:"golden",
        src:"assets/mp3/danci/golden.mp3"
    },
    {
        h:"棕色",
        e:"brown",
        src:"assets/mp3/danci/brown.mp3"
    },
    {
        h:"黄色",
        e:"yellow",
        src:"assets/mp3/danci/yellow.mp3"
    },
    {
        h:"粉色",
        e:"pink",
        src:"assets/mp3/danci/pink.mp3"
    },
    {
        h:"今天",
        e:"today",
        src:"assets/mp3/danci/today.mp3"
    },
    {
        h:"昨天",
        e:"yesterday",
        src:"assets/mp3/danci/yesterday.mp3"
    },
    {
        h:"明天",
        e:"tomorrow",
        src:"assets/mp3/danci/tomorrow.mp3"
    },
    {
        h:"天气",
        e:"weather",
        src:"assets/mp3/danci/weather.mp3"
    },
    {
        h:"阳光明媚",
        e:"sunny",
        src:"assets/mp3/danci/sunny.mp3"
    },
    {
        h:"下雨的",
        e:"rainy",
        src:"assets/mp3/danci/rainy.mp3"
    },
    {
        h:"多风的",
        e:"windy",
        src:"assets/mp3/danci/windy.mp3"
    },
    {
        h:"下雪",
        e:"snow",
        src:"assets/mp3/danci/snow.mp3"
    },
    {
        h:"身体",
        e:"body",
        src:"assets/mp3/danci/body.mp3"
    },
    {
        h:"头发",
        e:"hair",
        src:"assets/mp3/danci/hair.mp3"
    },
    {
        h:"头",
        e:"head",
        src:"assets/mp3/danci/head.mp3"
    },
    {
        h:"眼睛",
        e:"eye",
        src:"assets/mp3/danci/eye.mp3"
    },
    {
        h:"鼻子",
        e:"nose",
        src:"assets/mp3/danci/nose.mp3"
    },
    {
        h:"耳朵",
        e:"ear",
        src:"assets/mp3/danci/ear.mp3"
    },
    {
        h:"嘴巴",
        e:"mouth",
        src:"assets/mp3/danci/mouth.mp3"
    },
    {
        h:"脸",
        e:"face",
        src:"assets/mp3/danci/face.mp3"
    },
    {
        h:"胳膊",
        e:"arm",
        src:"assets/mp3/danci/arm.mp3"
    },
    {
        h:"手",
        e:"hand",
        src:"assets/mp3/danci/hand.mp3"
    },
    {
        h:"手指",
        e:"finger",
        src:"assets/mp3/danci/finger.mp3"
    },
    {
        h:"腿",
        e:"leg",
        src:"assets/mp3/danci/leg.mp3"
    },
    {
        h:"脚",
        e:"foot",
        src:"assets/mp3/danci/foot.mp3"
    },
    {
        h:"脚趾",
        e:"toe",
        src:"assets/mp3/danci/toe.mp3"
    },
    {
        h:"1",
        e:"one",
        src:"assets/mp3/danci/one.mp3"
    },
    {
        h:"2",
        e:"two",
        src:"assets/mp3/danci/two.mp3"
    },
    {
        h:"3",
        e:"three",
        src:"assets/mp3/danci/three.mp3"
    },
    {
        h:"4",
        e:"four",
        src:"assets/mp3/danci/four.mp3"
    },
    {
        h:"5",
        e:"five",
        src:"assets/mp3/danci/five.mp3"
    },
    {
        h:"6",
        e:"six",
        src:"assets/mp3/danci/six.mp3"
    },
    {
        h:"7",
        e:"seven",
        src:"assets/mp3/danci/seven.mp3"
    },
    {
        h:"8",
        e:"eight",
        src:"assets/mp3/danci/eight.mp3"
    },
    {
        h:"9",
        e:"nine",
        src:"assets/mp3/danci/nine.mp3"
    },
    {
        h:"10",
        e:"ten",
        src:"assets/mp3/danci/ten.mp3"
    },
    {
        h:"0",
        e:"zero",
        src:"assets/mp3/danci/zero.mp3"
    },
    {
        h:"春天",
        e:"spring",
        src:"assets/mp3/danci/spring.mp3"
    },
    {
        h:"温暖的",
        e:"warm",
        src:"assets/mp3/danci/warm.mp3"
    },
    {
        h:"夏天",
        e:"summer",
        src:"assets/mp3/danci/summer.mp3"
    },
    {
        h:"热",
        e:"hot",
        src:"assets/mp3/danci/hot.mp3"
    },
    {
        h:"秋天",
        e:"autumn",
        src:"assets/mp3/danci/autumn.mp3"
    },
    {
        h:"凉",
        e:"cool",
        src:"assets/mp3/danci/cool.mp3"
    },
    {
        h:"冬天",
        e:"winter",
        src:"assets/mp3/danci/winter.mp3"
    },
    {
        h:"冷的",
        e:"cold",
        src:"assets/mp3/danci/cold.mp3"
    },
    {
        h:"时间",
        e:"time",
        src:"assets/mp3/danci/time.mp3"
    },
    {
        h:"星期一",
        e:"Monday",
        src:"assets/mp3/danci/monday.mp3"
    },
    {
        h:"星期二",
        e:"Tuesday",
        src:"assets/mp3/danci/tuesday.mp3"
    },
    {
        h:"星期三",
        e:"Wednesday",
        src:"assets/mp3/danci/wednesday.mp3"
    },
    {
        h:"星期四",
        e:"Thursday",
        src:"assets/mp3/danci/thursday.mp3"
    },
    {
        h:"星期五",
        e:"Friday",
        src:"assets/mp3/danci/friday.mp3"
    },
    {
        h:"星期六",
        e:"Saturday",
        src:"assets/mp3/danci/saturday.mp3"
    },
    {
        h:"星期天",
        e:"Sunday",
        src:"assets/mp3/danci/sunday.mp3"
    },
    {
        h:"水果",
        e:"fruit",
        src:"assets/mp3/danci/fruit.mp3"
    },
    {
        h:"苹果",
        e:"apple",
        src:"assets/mp3/danci/apple.mp3"
    },
    {
        h:"香蕉",
        e:"banana",
        src:"assets/mp3/danci/banana.mp3"
    },
    {
        h:"桔子",
        e:"orange",
        src:"assets/mp3/danci/orange.mp3"
    },
    {
        h:"草莓",
        e:"strawberry",
        src:"assets/mp3/danci/strawberry.mp3"
    },
    {
        h:"西瓜",
        e:"watermelon",
        src:"assets/mp3/danci/watermelon.mp3"
    },
    {
        h:"芒果",
        e:"mango",
        src:"assets/mp3/danci/mango.mp3"
    },
    {
        h:"蔬菜",
        e:"vegetable",
        src:"assets/mp3/danci/vegetable.mp3"
    },
    {
        h:"土豆",
        e:"potato",
        src:"assets/mp3/danci/potato.mp3"
    },
    {
        h:"西红柿",
        e:"tomato",
        src:"assets/mp3/danci/tomato.mp3"
    },
    {
        h:"食物",
        e:"food",
        src:"assets/mp3/danci/food.mp3"
    },
    {
        h:"果汁",
        e:"juice",
        src:"assets/mp3/danci/juice.mp3"
    },
    {
        h:"冰淇淋",
        e:"Ice cream",
        src:"assets/mp3/danci/icecream.mp3"
    },
    {
        h:"水",
        e:"water",
        src:"assets/mp3/danci/water.mp3"
    },
    {
        h:"火",
        e:"fire",
        src:"assets/mp3/danci/fire.mp3"
    },
    {
        h:"面条",
        e:"noodles",
        src:"assets/mp3/danci/noodles.mp3"
    },
    {
        h:"饺子",
        e:"dumplings",
        src:"assets/mp3/danci/dumplings.mp3"
    },
    {
        h:"面包",
        e:"bread",
        src:"assets/mp3/danci/bread.mp3"
    },
    {
        h:"啤酒",
        e:"beer",
        src:"assets/mp3/danci/beer.mp3"
    },
    {
        h:"飞机",
        e:"airplane",
        src:"assets/mp3/danci/airplane.mp3"
    },
    {
        h:"小汽车",
        e:"car",
        src:"assets/mp3/danci/car.mp3"
    },
    {
        h:"公交车",
        e:"bus",
        src:"assets/mp3/danci/bus.mp3"
    },
    {
        h:"火车",
        e:"train",
        src:"assets/mp3/danci/train.mp3"
    },
    {
        h:"自行车",
        e:"bike",
        src:"assets/mp3/danci/bike.mp3"
    },
    {
        h:"天空",
        e:"sky",
        src:"assets/mp3/danci/sky.mp3"
    },
    {
        h:"鸟",
        e:"bird",
        src:"assets/mp3/danci/bird.mp3"
    },
    {
        h:"小猫",
        e:"cat",
        src:"assets/mp3/danci/cat.mp3"
    },
    {
        h:"小狗",
        e:"dog",
        src:"assets/mp3/danci/dog.mp3"
    },
    {
        h:"老虎",
        e:"tiger",
        src:"assets/mp3/danci/tiger.mp3"
    },
    {
        h:"狮子",
        e:"lion",
        src:"assets/mp3/danci/lion.mp3"
    },
    {
        h:"熊猫",
        e:"panda",
        src:"assets/mp3/danci/panda.mp3"
    },
    {
        h:"小猪",
        e:"pig",
        src:"assets/mp3/danci/pig.mp3"
    },
    {
        h:"猴子",
        e:"monkey",
        src:"assets/mp3/danci/monkey.mp3"
    },
    {
        h:"大象",
        e:"elephant",
        src:"assets/mp3/danci/elephant.mp3"
    },
    {
        h:"蜜蜂",
        e:"bee",
        src:"assets/mp3/danci/bee.mp3"
    },{
        h:"太阳",
        e:"sun",
        src:"assets/mp3/danci/sun.mp3"
    },
    {
        h:"月亮",
        e:"moon",
        src:"assets/mp3/danci/moon.mp3"
    },
    {
        h:"星星",
        e:"star",
        src:"assets/mp3/danci/star.mp3"
    },
    {
        h:"大的",
        e:"big",
        src:"assets/mp3/danci/big.mp3"
    },
    {
        h:"小的",
        e:"small",
        src:"assets/mp3/danci/small.mp3"
    },
    {
        h:"新的",
        e:"new",
        src:"assets/mp3/danci/new.mp3"
    },
    {
        h:"旧的",
        e:"old",
        src:"assets/mp3/danci/old.mp3"
    },
    {
        h:"男孩",
        e:"boy",
        src:"assets/mp3/danci/boy.mp3"
    },
    {
        h:"女孩",
        e:"girl",
        src:"assets/mp3/danci/girl.mp3"
    },
    {
        h:"弟弟",
        e:"brother",
        src:"assets/mp3/danci/brother.mp3"
    },
    {
        h:"姐姐",
        e:"sister",
        src:"assets/mp3/danci/sister.mp3"
    },
    {
        h:"老师",
        e:"teacher",
        src:"assets/mp3/danci/teacher.mp3"
    },
    {
        h:"医生",
        e:"doctor",
        src:"assets/mp3/danci/doctor.mp3"
    },{
        h:"门",
        e:"door",
        src:"assets/mp3/danci/door.mp3"
    },{
        h:"窗户",
        e:"window",
        src:"assets/mp3/danci/window.mp3"
    },{
        h:"课桌",
        e:"desk",
        src:"assets/mp3/danci/desk.mp3"
    },{
        h:"椅子",
        e:"chair",
        src:"assets/mp3/danci/chair.mp3"
    },{
        h:"沙发",
        e:"sofa",
        src:"assets/mp3/danci/sofa.mp3"
    },{
        h:"床",
        e:"bed",
        src:"assets/mp3/danci/bed.mp3"
    },
    {
        h:"茶杯",
        e:"cup",
        src:"assets/mp3/danci/cup.mp3"
    },
    {
        h:"花",
        e:"flower",
        src:"assets/mp3/danci/flower.mp3"
    },
    {
        h:"树",
        e:"tree",
        src:"assets/mp3/danci/tree.mp3"
    },
    {
        h:"牛奶",
        e:"milk",
        src:"assets/mp3/danci/milk.mp3"
    },
    {
        h:"大米",
        e:"rice",
        src:"assets/mp3/danci/rice.mp3"
    },
    {
        h:"看电视",
        e:"watch TV",
        src:"assets/mp3/danci/tv.mp3"
    },
    {
        h:"对不起",
        e:"I'm sorry",
        src:"assets/mp3/danci/iamsorry.mp3"
    },
    {
        h:"谢谢你",
        e:"Thank you",
        src:"assets/mp3/danci/thankyou.mp3"
    },
    {
        h:"晚安",
        e:"Good night",
        src:"assets/mp3/danci/goodnight.mp3"
    }
    
];

var letterList = document.getElementsByClassName("letterList")[0];
var letterBoxes = document.getElementsByClassName("letterBox");
var myAudio = document.getElementById("myAudio");
var icons = document.getElementsByClassName("icon");

for(var i=0;i<words.length;i++){
    letterList.innerHTML+='<div class="letterBox"><div class="icon"></div><i>'+(i+1)+'</i><span class="uppercase">'+words[i].h+'</span><div class="pronounce">'+words[i].e+'</div></div>';
}

for(var index=0;index<letterBoxes.length;index++){
    (function(i){
        letterBoxes[i].onclick = function(){
            // letterBoxes[i].style.borderColor = "#47cc9b";
            icons[i].style.backgroundImage = 'url(../pages/assets/play.gif)';
            myAudio.src = words[i].src;
            myAudio.play();
        }
    })(index)
}


myAudio.onended = function(){
    for(var j=0;j<icons.length;j++){
        icons[j].style.backgroundImage = 'url(../pages/assets/play.png)';
    }
}