window.onload = function(){
    // let articles = ['静夜思','春晓','咏鹅','登鹳雀楼','夜宿山寺','江雪','悯农二首·其一','悯农二首·其二','画','寻隐者不遇','鹿柴','独坐敬亭山','相思',
    // '宿建德江','登乐游原','逢雪宿芙蓉山主人','望庐山瀑布','竹里馆','绝句','风','鸟鸣涧','游子吟','赋得古原草送别','春夜喜雨','梅花','送灵澈上人','池上','山中送别',
    // '咏柳','清明','九月九日忆山东兄弟','望天门山','黄鹤楼送孟浩然之广陵','古朗月行','夏日绝句','七步诗','山村咏怀','问刘十九','早发白帝城','枫桥夜泊','回乡偶书','小池','早春呈水部张十八员外','出塞','村居','凉州词','赠汪伦','送元二使安西','黄鹤楼送孟浩然之广陵','晓出净慈寺送林子方',
    // '惠崇春江晚景','江南春','大林寺桃花','泊船瓜洲','元日','山行','江南'];
    

    var obj = [
        {
            "title":"春晓",
            "txt":"春晓，孟浩然，春眠不觉晓，处处闻啼鸟，夜来风雨声，花落知多少",
            "audioSrc":"../assets/mp3/ts/ts1.mp3"
        },
        {
            "title":"悯农其一",
            "txt":"悯农其一，李绅，春种一粒粟，秋收万颗子，四海无闲田，农夫犹饿死",
            "audioSrc":"../assets/mp3/ts/ts6.mp3"
        },
        {
            "title":"悯农其二",
            "txt":"悯农其二，李绅，锄禾日当午，汗滴禾下土，谁知盘中餐，粒粒皆辛苦",
            "audioSrc":"../assets/mp3/ts/ts7.mp3"
        },
        {
            "title":"梅花",
            "txt":"梅花，王安石，墙角数枝梅，凌寒独自开，遥知不是雪，为有暗香来",
            "audioSrc":"../assets/mp3/ts/ts24.mp3"
        },
        {
            "title":"夜宿山寺",
            "txt":"夜宿山寺，李白，危楼高百尺，手可摘星辰，不敢高声语，恐惊天上人",
            "audioSrc":"../assets/mp3/ts/ts4.mp3"
        },
        {
            "title":"独坐敬亭山",
            "txt":"独坐敬亭山，李白，众鸟高飞尽，孤云独去闲，相看两不厌，只有敬亭山",
            "audioSrc":"../assets/mp3/ts/ts11.mp3"
        },
        {
            "title":"送灵澈上人",
            "txt":"送灵澈上人，刘长卿，苍苍竹林寺，杳杳钟声晚，荷笠带斜阳，青山独归远",
            "audioSrc":"../assets/mp3/ts/ts25.mp3"
        },
        {
            "title":"春夜喜雨-杜甫",
            "txt":"春夜喜雨，杜甫，好雨知时节，当春乃发生，随风潜入夜，润物细无声",
            "audioSrc":"../assets/mp3/ts/ts23.mp3"
        },
        {
            "title":"宿建德江",
            "txt":"宿建德江，孟浩然，移舟泊烟渚，日暮客愁新，野旷天低树，江清月近人",
            "audioSrc":"../assets/mp3/ts/ts13.mp3"
        },
        {
            "title":"登乐游原",
            "txt":"登乐游原，李商隐，向晚意不适，驱车登古原，夕阳无限好，只是近黄昏",
            "audioSrc":"../assets/mp3/ts/ts14.mp3"
        },
        {
            "title":"山中送别",
            "txt":"山中送别，王维，山中相送罢，日暮掩柴扉，春草明年绿，王孙归不归",
            "audioSrc":"../assets/mp3/ts/ts27.mp3"
        },
        {
            "title":"池上-白居易",
            "txt":"池上，白居易，小娃撑小艇，偷采白莲回，不解藏踪迹，浮萍一道开",
            "audioSrc":"../assets/mp3/ts/ts26.mp3"
        },
        {
            "title":"游子吟",
            "txt":"游子吟，孟郊，慈母手中线，游子身上衣，临行密密缝，意恐迟迟归，谁言寸草心，报得三春晖",
            "audioSrc":"../assets/mp3/ts/ts21.mp3"
        },
        {
            "title":"风",
            "txt":"风，李峤，解落三秋叶，能开二月花，过江千尺浪，入竹万竿斜",
            "audioSrc":"../assets/mp3/ts/ts19.mp3"
        },
        {
            "title":"竹里馆",
            "txt":"竹里馆，王维，独坐幽篁里，弹琴复长啸，深林人不知，明月来相照",
            "audioSrc":"../assets/mp3/ts/ts17.mp3"
        },
        {
            "title":"鸟鸣涧",
            "txt":"鸟鸣涧，王维，人闲桂花落，夜静春山空，月出惊山鸟，时鸣春涧中",
            "audioSrc":"../assets/mp3/ts/ts20.mp3"
        },
        {
            "title":"绝句",
            "txt":"绝句，杜甫，两个黄鹂鸣翠柳，一行白鹭上青天，窗含西岭千秋雪，门泊东吴万里船",
            "audioSrc":"../assets/mp3/ts/ts18.mp3"
        },
        {
            "title":"画-王维",
            "txt":"画，王维，远看山有色，近听水无声，春去花还在，人来鸟不惊",
            "audioSrc":"../assets/mp3/ts/ts8.mp3"
        },
        {
            "title":"寻隐者不遇-贾岛",
            "txt":"寻隐者不遇，贾岛，松下问童子，言师采药去，只在此山中，云深不知处",
            "audioSrc":"../assets/mp3/ts/ts9.mp3"
        },
        {
            "title":"江南-汉乐府",
            "txt":"江南，汉乐府，江南可采莲，莲叶何田田，鱼戏莲叶间，鱼戏莲叶东，鱼戏莲叶西，鱼戏莲叶南，鱼戏莲叶北",
            "audioSrc":"../assets/mp3/ts/ts56.mp3"
        },
        {
            "title":"画鸡",
            "txt":"画鸡，明朝 唐寅，头上红冠不用裁，满身雪白走将来，平生不敢轻言语，一叫千门万户开",
            "audioSrc":"../assets/mp3/ts/ts57.mp3"
        },
        {
            "title":"静夜思",
            "txt":"静夜思，李白，床前明月光，疑是地上霜，举头望明月，低头思故乡",
            "audioSrc":"../assets/mp3/ts/ts0.mp3"
        },
        {
            "title":"咏鹅",
            "txt":"咏鹅，骆宾王，鹅鹅鹅，曲项向天歌，白毛浮绿水，红掌拨清波",
            "audioSrc":"../assets/mp3/ts/ts2.mp3"
        },
        {
            "title":"登鹳雀楼",
            "txt":"登鹳雀楼，王之涣，白日依山尽，黄河入海流，欲穷千里目，更上一层楼",
            "audioSrc":"../assets/mp3/ts/ts3.mp3"
        },
        {
            "title":"江雪",
            "txt":"江雪，柳宗元，千山鸟飞绝，万径人踪灭，孤舟蓑笠翁，独钓寒江雪",
            "audioSrc":"../assets/mp3/ts/ts5.mp3"
        },
        {
            "title":"鹿柴",
            "txt":"鹿柴，王维，空山不见人，但闻人语响，返景入深林，复照青苔上",
            "audioSrc":"../assets/mp3/ts/ts10.mp3"
        },
        {
            "title":"相思",
            "txt":"相思，王维，红豆生南国，春来发几枝，愿君多采撷，此物最相思",
            "audioSrc":"../assets/mp3/ts/ts12.mp3"
        },
        {
            "title":"逢雪宿芙蓉山主人",
            "txt":"逢雪宿芙蓉山主人，刘长卿，日暮苍山远，天寒白屋贫，柴门闻犬吠，风雪夜归人",
            "audioSrc":"../assets/mp3/ts/ts15.mp3"
        },
        {
            "title":"望庐山瀑布",
            "txt":"望庐山瀑布，李白，日照香炉生紫烟，遥看瀑布挂前川，飞流直下三千尺，疑是银河落九天",
            "audioSrc":"../assets/mp3/ts/ts16.mp3"
        },
        {
            "title":"赋得古原草送别",
            "txt":"赋得古原草送别，白居易，离离原上草，一岁一枯荣，野火烧不尽，春风吹又生",
            "audioSrc":"../assets/mp3/ts/ts22.mp3"
        },
        {
            "title":"咏柳",
            "txt":"咏柳，贺知章，碧玉妆成一树高，万条垂下绿丝绦，不知细叶谁裁出，二月春风似剪刀",
            "audioSrc":"../assets/mp3/ts/ts28.mp3"
        },
        {
            "title":"清明",
            "txt":"清明，杜牧，清明时节雨纷纷，路上行人欲断魂，借问酒家何处有，牧童遥指杏花村",
            "audioSrc":"../assets/mp3/ts/ts29.mp3"
        },
        {
            "title":"九月九日忆山东兄弟",
            "txt":"九月九日忆山东兄弟，王维，独在异乡为异客，每逢佳节倍思亲，遥知兄弟登高处，遍插茱萸少一人",
            "audioSrc":"../assets/mp3/ts/ts30.mp3"
        },
        {
            "title":"望天门山",
            "txt":"望天门山，李白，天门中断楚江开，碧水东流至此回，两岸青山相对出，孤帆一片日边来",
            "audioSrc":"../assets/mp3/ts/ts31.mp3"
        },
        {
            "title":"黄鹤楼送孟浩然之广陵",
            "txt":"黄鹤楼送孟浩然之广陵，李白，故人西辞黄鹤楼，烟花三月下扬州，孤帆远影碧空尽，唯见长江天际流",
            "audioSrc":"../assets/mp3/ts/ts32.mp3"
        },
        {
            "title":"古朗月行",
            "txt":"古朗月行，李白，小时不识月，呼作白玉盘，又疑瑶台镜，飞在青云端",
            "audioSrc":"../assets/mp3/ts/ts33.mp3"
        },
        {
            "title":"夏日绝句",
            "txt":"夏日绝句，李清照，生当作人杰，死亦为鬼雄，至今思项羽，不肯过江东",
            "audioSrc":"../assets/mp3/ts/ts34.mp3"
        },
        {
            "title":"七步诗",
            "txt":"七步诗，曹植，煮豆燃豆萁，豆在釜中泣，本自同根生，相煎何太急",
            "audioSrc":"../assets/mp3/ts/ts35.mp3"
        },
        {
            "title":"山村咏怀",
            "txt":"山村咏怀，宋·邵雍，一去二三里，烟村四五家，亭台六七座，八九十枝花",
            "audioSrc":"../assets/mp3/ts/ts36.mp3"
        },
        {
            "title":"问刘十九",
            "txt":"问刘十九，白居易，绿蚁新醅酒，红泥小火炉，晚来天欲雪，能饮一杯无",
            "audioSrc":"../assets/mp3/ts/ts37.mp3"
        },
        {
            "title":"早发白帝城",
            "txt":"早发白帝城，李白，朝辞白帝彩云间，千里江陵一日还，两岸猿声啼不住，轻舟已过万重山",
            "audioSrc":"../assets/mp3/ts/ts38.mp3"
        },
        {
            "title":"枫桥夜泊",
            "txt":"枫桥夜泊，张继，月落乌啼霜满天，江枫渔火对愁眠，姑苏城外寒山寺，夜半钟声到客船",
            "audioSrc":"../assets/mp3/ts/ts39.mp3"
        },
        {
            "title":"回乡偶书",
            "txt":"回乡偶书，贺知章，少小离家老大回，乡音无改鬓毛衰，儿童相见不相识，笑问客从何处来",
            "audioSrc":"../assets/mp3/ts/ts40.mp3"
        },
        {
            "title":"小池",
            "txt":"小池，杨万里，泉眼无声惜细流，树阴照水爱晴柔，小荷才露尖尖角，早有蜻蜓立上头",
            "audioSrc":"../assets/mp3/ts/ts41.mp3"
        },
        {
            "title":"早春呈水部张十八员外",
            "txt":"早春呈水部张十八员外，韩愈，天街小雨润如酥，草色遥看近却无，最是一年春好处，绝胜烟柳满皇都",
            "audioSrc":"../assets/mp3/ts/ts42.mp3"
        },
        {
            "title":"出塞",
            "txt":"出塞，王昌龄，秦时明月汉时关，万里长征人未还，但使龙城飞将在，不教胡马度阴山",
            "audioSrc":"../assets/mp3/ts/ts43.mp3"
        },
        {
            "title":"村居",
            "txt":"村居，高鼎，草长莺飞二月天，拂堤杨柳醉春烟，儿童散学归来早，忙趁东风放纸鸢",
            "audioSrc":"../assets/mp3/ts/ts44.mp3"
        },
        {
            "title":"凉州词",
            "txt":"凉州词，王翰，葡萄美酒夜光杯，欲饮琵琶马上催，醉卧沙场君莫笑，古来征战几人回",
            "audioSrc":"../assets/mp3/ts/ts45.mp3"
        },
        {
            "title":"赠汪伦",
            "txt":"赠汪伦，李白，李白乘舟将欲行，忽闻岸上踏歌声，桃花潭水深千尺，不及汪伦送我情",
            "audioSrc":"../assets/mp3/ts/ts46.mp3"
        },
        {
            "title":"送元二使安西",
            "txt":"送元二使安西，王维，渭城朝雨浥轻尘，客舍青青柳色新，劝君更尽一杯酒，西出阳关无故人",
            "audioSrc":"../assets/mp3/ts/ts47.mp3"
        },
        {
            "title":"黄鹤楼送孟浩然之广陵",
            "txt":"黄鹤楼送孟浩然之广陵，李白，故人西辞黄鹤楼，烟花三月下扬州，孤帆远影碧空尽，唯见长江天际流",
            "audioSrc":"../assets/mp3/ts/ts48.mp3"
        },
        {
            "title":"晓出净慈寺送林子方",
            "txt":"晓出净慈寺送林子方，杨万里，毕竟西湖六月中，风光不与四时同，接天莲叶无穷碧，映日荷花别样红",
            "audioSrc":"../assets/mp3/ts/ts49.mp3"
        },
        {
            "title":"惠崇春江晚景",
            "txt":"惠崇春江晚景，苏轼，竹外桃花三两枝，春江水暖鸭先知，蒌蒿满地芦芽短，正是河豚欲上时",
            "audioSrc":"../assets/mp3/ts/ts50.mp3"
        },
        {
            "title":"江南春",
            "txt":"江南春，杜牧，千里莺啼绿映红，水村山郭酒旗风，南朝四百八十寺，多少楼台烟雨中",
            "audioSrc":"../assets/mp3/ts/ts51.mp3"
        },
        {
            "title":"大林寺桃花",
            "txt":"大林寺桃花，白居易，人间四月芳菲尽，山寺桃花始盛开，长恨春归无觅处，不知转入此中来",
            "audioSrc":"../assets/mp3/ts/ts52.mp3"
        },
        {
            "title":"泊船瓜洲",
            "txt":"泊船瓜洲，王安石，京口瓜洲一水间，钟山只隔数重山，春风又绿江南岸，明月何时照我还",
            "audioSrc":"../assets/mp3/ts/ts53.mp3"
        },
        {
            "title":"元日",
            "txt":"元日，王安石，爆竹声中一岁除，春风送暖入屠苏，千门万户曈曈日，总把新桃换旧符",
            "audioSrc":"../assets/mp3/ts/ts54.mp3"
        },
        {
            "title":"山行",
            "txt":"山行，杜牧，远上寒山石径斜，白云生处有人家，停车坐爱枫林晚，霜叶红于二月花",
            "audioSrc":"../assets/mp3/ts/ts55.mp3"
        }
    ];

    let articles = [];
    for(var n=0;n<obj.length;n++){
        articles.push(obj[n].title);
    }
    var num = document.getElementById('num');
    num.innerHTML = '共'+articles.length+'首';

    let j;
    for( j=0;j<articles.length;j++){
      document.getElementsByTagName('ul')[0].innerHTML+='<li><a href="tangshi.html">'+articles[j]+'</a></li>';
    }

    let lists = document.getElementsByTagName('li');
    // let num = lists.length;
    console.log(lists);
    for(let i=0;i<lists.length;i++){
        lists[i].onclick = function(){
            sessionStorage.setItem('tangshi', obj[i].txt);
            sessionStorage.setItem('audioSrc', obj[i].audioSrc);
        }
    }
}